{"uuid": "a9b4b815-43bb-436b-a742-efdca7a9f1e3", "children": ["92faf9b9-5a3f-4037-989f-622ea4fed4a6", "4e4d5565-57b7-431f-aa3d-437c55984d67"], "befores": [{"name": "_xunit_setup_class_fixture_TestAddMember", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: Could not start a new session. New session request timed out \nHost info: host: '772c8f4708ad', ip: '172.17.0.3'\nBuild info: version: '4.10.0', revision: 'c14d967899'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '5.19.0-43-generic', java.version: '11.0.19'\nDriver info: driver.version: unknown\nStacktrace:\n    at org.openqa.selenium.grid.sessionqueue.local.LocalNewSessionQueue.addToQueue (LocalNewSessionQueue.java:213)\n    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.lambda$new$0 (NewSessionQueue.java:68)\n    at org.openqa.selenium.remote.http.Route$TemplatizedRoute.handle (Route.java:193)\n    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)\n    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:347)\n    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)\n    at org.openqa.selenium.grid.sessionqueue.NewSessionQueue.execute (NewSessionQueue.java:121)\n    at org.openqa.selenium.remote.tracing.SpanWrappedHttpHandler.execute (SpanWrappedHttpHandler.java:91)\n    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)\n    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:347)\n    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)\n    at org.openqa.selenium.grid.router.Router.execute (Router.java:87)\n    at org.openqa.selenium.grid.web.EnsureSpecCompliantResponseHeaders.lambda$apply$0 (EnsureSpecCompliantResponseHeaders.java:34)\n    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)\n    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:347)\n    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)\n    at org.openqa.selenium.remote.http.Route$NestedRoute.handle (Route.java:271)\n    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)\n    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:347)\n    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)\n    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:347)\n    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)\n    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:347)\n    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)\n    at org.openqa.selenium.remote.http.Route$CombinedRoute.handle (Route.java:347)\n    at org.openqa.selenium.remote.http.Route.execute (Route.java:69)\n    at org.openqa.selenium.remote.AddWebDriverSpecHeaders.lambda$apply$0 (AddWebDriverSpecHeaders.java:35)\n    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)\n    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)\n    at org.openqa.selenium.remote.ErrorFilter.lambda$apply$0 (ErrorFilter.java:44)\n    at org.openqa.selenium.remote.http.Filter$1.execute (Filter.java:63)\n    at org.openqa.selenium.netty.server.SeleniumHandler.lambda$channelRead0$0 (SeleniumHandler.java:44)\n    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)\n    at java.util.concurrent.FutureTask.run (FutureTask.java:264)\n    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)\n    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)\n    at java.lang.Thread.run (Thread.java:829)\n", "trace": "  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\_pytest\\python.py\", line 864, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\_pytest\\python.py\", line 785, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\pycharm\\Selenium\\testcase\\test_add_member.py\", line 12, in setup_class\n    self.home = LoginPage().login()\n  File \"D:\\pycharm\\Selenium\\page\\base.py\", line 21, in __init__\n    self.driver = webdriver.Remote(command_executor='http://192.168.254.128:5444/wd/hub', desired_capabilities=DesiredCapalities)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 365, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\pycharm\\Selenium\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1690513547458, "stop": 1690513847504}], "start": 1690513547458, "stop": 1690513847735}