{"name": "test_add_member_from_homepage", "status": "broken", "statusDetails": {"message": "TypeError: __init__() got an unexpected keyword argument 'capabilities'", "trace": "self = <class 'testcase.test_add_member.TestAddMember'>\n\n    def setup_class(self):\n        # 登录\n>       self.home = LoginPage().login()\n\ntestcase\\test_add_member.py:12: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page.login_page.LoginPage object at 0x000002610F596700>, base_driver = None\n\n    def __init__(self, base_driver=None):\n        if base_driver:\n            self.driver = base_driver\n        else:\n            # self.driver = webdriver.Chrome()\n            capabilities = {'browserName':'Chrome'}\n>           self.driver = webdriver.Remote(command_executor='http://192.168.254.128:5444/wd/hub', capabilities=capabilities)\nE           TypeError: __init__() got an unexpected keyword argument 'capabilities'\n\npage\\base.py:21: TypeError"}, "start": 1690513521123, "stop": 1690513521123, "uuid": "c770ce18-6683-418c-809b-7aebb8da56b2", "historyId": "b003135152d87188c72a91ecc7e15c63", "testCaseId": "b003135152d87188c72a91ecc7e15c63", "fullName": "testcase.test_add_member.TestAddMember#test_add_member_from_homepage", "labels": [{"name": "story", "value": "主页入口添加成员"}, {"name": "feature", "value": "添加成员"}, {"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_add_member"}, {"name": "subSuite", "value": "TestAddMember"}, {"name": "host", "value": "DESKTOP-7Q67NG8"}, {"name": "thread", "value": "59220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_add_member"}]}